name: wayburger
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
  dotenv: ^4.2.0
  mysql: ^0.19.2
  shelf_static: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.1.4
  shelf_router_generator: ^1.0.1
